load("//xla/tsl/platform:rules_cc.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "vulkan_platform_id",
    srcs = ["vulkan_platform_id.cc"],
    hdrs = ["vulkan_platform_id.h"],
    deps = ["//xla/stream_executor:platform"],
)
